# Generated by Django 5.2 on 2025-04-05 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='Document Creation or Generation Date', null=True, verbose_name='created'),
        ),
    ]
