# Generated by Django 5.2 on 2025-04-08 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='documents.document', verbose_name='document'),
        ),
    ]
