# Generated by Django 5.2 on 2025-04-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_deleted_at_document_restored_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Document Creation or Generation Date', null=True, verbose_name='created'),
        ),
    ]
